# Dockerfile.dev
FROM cpp-dev-env:boost-1-83

# Update and install dependencies
RUN apt-get update && apt-get install -y \
    cmake \
    sqlite3 \
    libsqlite3-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Default command
CMD ["/bin/bash"]
